# Term Tools
brew "lsd"
brew "zoxide"
brew "fzf"
brew "tree"
brew "ripgrep"

# Dev Tools
brew "neovim"
brew "git"
brew "bottom"

# macOS Enviroment
cask "nikitabobko/tap/aerospace"
cask "linearmouse"

# Applications
cask "bitwarden"
cask "discord"
cask "font-hack-nerd-font"
cask "zen-browser"

# Tap Utils
tap "homebrew/bundle"

# MAS
brew "mas"
mas "Klack", id: 6446206067

