# Term Tools

# Dev Tools
brew "git"
brew "neovim"

# macOS Enviroment
cask "font-hack-nerd-font"
cask "nikitabobko/tap/aerospace"

# Applications
cask "bitwarden"

# MAS
brew "mas"
mas "Klack", id: 6446206067

